# Generated by Django 5.0.2 on 2024-03-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accounts',
            field=models.ManyToManyField(to='accounts.account'),
        ),
    ]
