# Generated by Django 5.0.2 on 2024-03-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_token_user'),
    ]

    operations = [
    ]
